In [1]:
import pandas as pd
import numpy as np
import re

In [51]:
matches = \
pd.read_json('https://raw.githubusercontent.com/mesosbrodleto/soccerDataChallenge/master/worldCup-final.json')

players = \
pd.read_json('https://raw.githubusercontent.com/mesosbrodleto/soccerDataChallenge/master/players.json')

In [9]:
matches.info() # NON LO METTO NEL FILE

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1547 entries, 0 to 1546
Data columns (total 12 columns):
eventId         1547 non-null int64
eventName       1547 non-null object
eventSec        1547 non-null float64
id              1547 non-null int64
matchId         1547 non-null int64
matchPeriod     1547 non-null object
playerId        1547 non-null int64
positions       1547 non-null object
subEventId      1547 non-null object
subEventName    1547 non-null object
tags            1547 non-null object
teamId          1547 non-null object
dtypes: float64(1), int64(4), object(7)
memory usage: 157.1+ KB

In [131]:
matches.groupby(['eventName', 'subEventName']).agg({'id': np.size}).rename(columns={'id': 'n_elements'})

# NON LO METTO NEL FILE

                                                 n_elements
eventName               subEventName
Duel                    Air duel                         82
                        Ground attacking duel           125
                        Ground defending duel           125
                        Ground loose ball duel           58
Foul                    Foul                             24
                        Hand foul                         2
Free Kick               Corner                            8
                        Free Kick                        20
                        Free kick cross                   7
                        Goal kick                        18
                        Penalty                           1
                        Throw in                         46
Goalkeeper leaving line Goalkeeper leaving line           5
Interruption            Ball out of the field            72
                        Whistle                           4
Offside                                                   2
Others on the ball      Acceleration                     25
                        Clearance                        29
                        Touch                           104
Pass                    Cross                            27
                        Hand pass                         7
                        Head pass                        61
                        High pass                        54
                        Launch                           25
                        Simple pass                     570
                        Smart pass                       14
Save attempt            Reflexes                          6
                        Save attempt                      4
Shot                    Shot                             21

In [11]:
matches.eventName.value_counts() # NON LO METTO NEL FILE

Pass                       759
Duel                       390
Others on the ball         158
Free Kick                  100
Interruption                76
Foul                        26
Shot                        21
Save attempt                10
Goalkeeper leaving line      5
Offside                      2
Name: eventName, dtype: int64

ESERCIZIO:
Calcolare la posizione media di ogni calciatore che abbia giocato almeno 45 minuti. Calcolare inoltre la distanza quadratica media di ogni giocatore rispetto alla sua posizione media. Calcolare, per ogni giocatore, il tempo medio che passa tra due eventi del giocatore (in secondi).

In [71]:
# add 45 * 60 minutes for events in the second half
matches.eventSec = matches.eventSec + matches.matchPeriod.apply(lambda s: 0 if s[0] == '1' else 45 * 60)
no_players = [k for k, v in (matches.groupby('playerId').agg({'teamId': 'nunique'}).teamId < 2).to_dict().items() 
              if not v]
matches.drop(no_players, inplace=True)

In [33]:
players_45min = matches\
.groupby('playerId', as_index=False).agg({"eventSec": [np.max, np.min]})\
.assign(playing_time=lambda  x: (x[('eventSec', 'amax')] - x[('eventSec', 'amin')]) / 60)\
.loc[:, ['playerId', 'playing_time']]

sommatoria, **per ogni posizione p del calciatore**, della distanza al quadrato tra la posizione p e la posizione media, fratto **il numero totale di eventi del calciatore** nella partita

In [34]:
player_45min_ids = players_45min[players_45min.playing_time >= 45].playerId.values
matches = matches.loc[matches.playerId.isin(player_45min_ids)]

def extract_position(series_pos):
    ys = np.array([d['y'] for line in series_pos.values for d in line])
    xs = np.array([d['x'] for line in series_pos.values for d in line])
    y_mean = ys.mean()
    x_mean = xs.mean()
    dist = np.power(ys - y_mean, 2) + np.power(xs - x_mean, 2)
    return pd.DataFrame([[x_mean, y_mean, dist.sum() / len(series_pos)]],
                       columns=['posizione_media_x', 'posizione_media_y', 'distanza_quadratica_media'])

result1 = matches.groupby('playerId').positions.apply(extract_position)
result1.index = result1.index.droplevel(1)

In [41]:
def extract_time_delta(series_time):
    return np.mean(series_time - series_time.shift(1))

result2 = matches.groupby('playerId').eventSec.apply(extract_time_delta).rename('tempo_medio_tra_eventi')

In [52]:
matches[['playerId', 'teamId']].drop_duplicates('playerId')\
.merge(players, how='left', on='playerId')\
.merge(pd.concat((result1, result2), axis=1).reset_index(), how='left', on='playerId')\
.rename(columns={'playerId': 'identificativo_calciatore',
                 'name': 'nome_calciatore',
                 'teamId': 'squadra_calciatore'})\
.loc[:, ['identificativo_calciatore', 'nome_calciatore', 'squadra_calciatore', 'posizione_media_x',
         'posizione_media_y', 'distanza_quadratica_media', 'tempo_medio_tra_eventi']]\
.to_csv('problema_1.csv', index=False)

In [45]:
players[players.playerId == 31528]

Empty DataFrame
Columns: [name, playerId]
Index: []

# ======================================

ESERCIZIO (a):
Dividere il campo di gioco in una griglia 5x5 (ossia in 25 celle di uguale dimensione). Per ogni cella e per ogni squadra calcolare:
i. Frequenza degli eventi effettuati (numero di eventi in quella cella sul totale degli eventi della squadra)
ii. Frequenza di passaggi accurati effettuati (numero di passaggi accurati in quella cella sul totale dei passaggi accurati)
iii. Frequenza di tiri effettuati 
iv. Frequenza di falli subiti

In [106]:
def transform_tags(l):
    if len(l) == 0:
        return np.nan
    elif 1801 in list(l[0].values()):
        return 'accurate'
    return 'non_accurate'

matches.tags = matches.tags.apply(transform_tags)

In [59]:
def extract_positions(pos_series):
    pos_list = pos_series.tolist()[0]
    try:
        y_end = pos_list[1]['y']
        x_end = pos_list[1]['x']
    except:
        y_end = np.nan
        x_end = np.nan
    y_start = pos_list[0]['y']
    x_start = pos_list[0]['x']
    return pd.DataFrame([[x_start, y_start, x_end, y_end]], columns=['x_start', 'y_start', 'x_end', 'y_end'])

positions = matches.groupby('id').positions.apply(extract_positions)
positions.index = positions.index.droplevel(1)
matches = matches.merge(positions.reset_index(), on='id')

In [108]:
def cell_number(pos):
    return (pos / 20.01).astype('int')

cells = matches.set_index('id').iloc[:, -4:].apply(cell_number)

matches_with_cell_numbers = pd.concat((cells.iloc[:, :2].rename(columns={'x_start': 'numero_cella_x',
                                             'y_start': 'numero_cella_y'}), 
           cells.iloc[:, -2:].rename(columns={'x_end': 'numero_cella_x',
                                             'y_end': 'numero_cella_y'})
          )).reset_index()\
.merge(matches, on='id')


r1 = matches_with_cell_numbers.groupby(['teamId', 'numero_cella_x', 'numero_cella_y']).agg({'id': 'nunique'})\
.rename(columns={'id': 'frequenza_eventi'})

r2 = matches_with_cell_numbers[(matches_with_cell_numbers.tags == 'accurate') &
                               (matches_with_cell_numbers.eventName == 'Pass')]\
.groupby(['teamId', 'numero_cella_x', 'numero_cella_y']).agg({'id': 'nunique'})\
.rename(columns={'id': 'frequenza_passaggi_accurati'})

In [147]:
total = pd.concat((r1,
           r2,  
           matches_with_cell_numbers[matches_with_cell_numbers.eventName == "Shot"]\
           .groupby(['teamId', 'numero_cella_x', 'numero_cella_y']).agg({'id': 'nunique'})\
           .rename(columns={'id': 'frequenza_tiri'}),
           
           matches_with_cell_numbers[matches_with_cell_numbers.eventName == 'Foul']\
           .groupby(['teamId', 'numero_cella_x', 'numero_cella_y']).agg({'id': 'nunique'})\
           .rename(columns={'id': 'frequenza_falli'})
          ), axis=1).fillna(0).reset_index().rename(columns={'teamId': 'nome_squadra'})

for c in total.columns[-4:]:
    for s in total.nome_squadra.unique():
        total.loc[(total.nome_squadra == s), c] = \
        (total.loc[(total.nome_squadra == s), c] / total.loc[(total.nome_squadra == s), c].sum()).round(2)
        
total.to_csv('problema_3_a.csv', index=False)

## problema B

In [152]:
from scipy.spatial.distance import cosine

total = pd.read_csv('problema_3_a.csv')

In [154]:
similarities = []

for c in total.columns[-4:]:
    res = cosine(total.loc[total.nome_squadra == 'Croatia', c].values, 
                 total.loc[total.nome_squadra == 'France', c].values)
    similarities.append(res)

In [160]:
pd.DataFrame(list(zip(range(1,5), similarities)), columns=['tipo_griglia','similarity']).to_csv('problema_3_b.csv',
                                                                                               index=False)

## problema C
Calcolare la squadra “dominante” in ogni cella delle griglia costruita secondo il punto (a)-i. Una squadra è “dominante” in una cella se il suo valore di frequenza è maggiore di quello della squadra avversaria

In [225]:
total = pd.read_csv('problema_3_a.csv').set_index(['numero_cella_x', 'numero_cella_y'])
origin =  (total.loc[total.nome_squadra == 'France', 'frequenza_eventi'] - total.loc[total.nome_squadra == 'Croatia',
                                                                                     'frequenza_eventi'])

for c in total.columns[-3:]:
    origin = pd.concat((origin,
               total.loc[total.nome_squadra == 'France', c] - total.loc[total.nome_squadra == 'Croatia', c]
              ), axis=1)

/Users/stefanocalde/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/ipykernel_launcher.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.

/Users/stefanocalde/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/ipykernel_launcher.py:3: PerformanceWarning: indexing past lexsort depth may impact performance.
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/stefanocalde/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/ipykernel_launcher.py:7: PerformanceWarning: indexing past lexsort depth may impact performance.
  import sys

In [226]:
origin

                               frequenza_eventi  frequenza_passaggi_accurati  \
numero_cella_x numero_cella_y
0              0                           0.04                         0.01
               1                           0.01                         0.01
               2                           0.03                         0.01
               3                           0.01                        -0.01
               4                           0.02                         0.00
1              0                           0.03                         0.05
               1                           0.02                         0.06
               2                           0.00                        -0.01
               3                          -0.01                        -0.01
               4                          -0.01                        -0.03
2              0                           0.01                         0.02
               1                           0.00                         0.05
               2                          -0.01                        -0.01
               3                          -0.02                        -0.03
               4                           0.02                         0.04
3              0                           0.01                        -0.01
               1                          -0.02                        -0.04
               2                           0.01                        -0.01
               3                          -0.02                        -0.05
               4                          -0.02                        -0.02
4              0                          -0.01                        -0.01
               1                          -0.02                         0.00
               2                          -0.02                         0.00
               3                           0.01                         0.01
               4                          -0.06                        -0.01

                               frequenza_tiri  frequenza_falli
numero_cella_x numero_cella_y
0              0                         0.50             0.06
               1                         0.00             0.00
               2                         0.00            -0.05
               3                         0.00             0.00
               4                         0.00            -0.05
1              0                         0.00             0.20
               1                         0.00            -0.14
               2                         0.00             0.06
               3                         0.00             0.00
               4                         0.00             0.14
2              0                         0.00             0.01
               1                         0.00            -0.14
               2                         0.00             0.01
               3                         0.00             0.06
               4                         0.00            -0.10
3              0                         0.00             0.01
               1                        -0.07             0.06
               2                         0.03             0.07
               3                         0.10            -0.10
               4                         0.00            -0.05
4              0                         0.00             0.00
               1                        -0.11             0.00
               2                         0.00             0.00
               3                         0.03            -0.05
               4                        -0.50            -0.05

In [227]:
origin.columns = range(1, 5)
origin = origin.stack().reset_index().rename(columns={'level_2': 'tipo_griglia', 0:'differenza_di_frequenza'})
origin['squadra_dominante'] = origin.differenza_di_frequenza.apply(lambda b: 'France' if b >= 0 else 'Croatia')
origin.differenza_di_frequenza = origin.differenza_di_frequenza.abs()

origin.loc[:, ['tipo_griglia', 'numero_cella_x', 'numero_cella_y', 'squadra_dominante', 'differenza_di_frequenza']]\
.to_csv('problema_3_c.csv', index=False)